const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOAD_DATA = 'LOAD_DATA';
const ERROR_MSG = 'ERROR_MSG';

export { REGISTER_SUCCESS, LOGIN_SUCCESS, LOAD_DATA, ERROR_MSG };