// user
const LOAD_DATA = 'LOAD_DATA';
const ERROR_MSG = 'ERROR_MSG';
const AUTH_SUCCESS = 'AUTH_SUCCESS';
const USER_LIST = 'USER_LIST';
const LOGOUT = 'LOGOUT';

// chat
const MSG_LIST = 'MSG_LIST';
const MSG_RECV = 'MSG_RECV';
const MSG_READ = 'MSG_READ';

export { AUTH_SUCCESS, LOAD_DATA, ERROR_MSG, USER_LIST, LOGOUT, MSG_LIST, MSG_READ, MSG_RECV };